[Logger Settings]
log_path = ./utils/logger/logs/
log_name = log.log
#Debug Message Formatting can be found at: https://docs.python.org/3/library/logging.html#formatter-objects
log_format = %(asctime)s | %(module)s -> %(funcName)s [%(levelname)s] : %(message)s
#Minimum Accepted Level to pass to log file: 
#DEBUG -> INFO -> WARNING -> ERROR -> CRITICAL (All levels to the right are also passed)
log_level = DEBUG