[project]
name = "sx-con"
version = "0.1.0"
description = ""
authors = [
    {name = "ifndefy",email = "lee.sjoe.3@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyodbc (==5.3.0)",
    "azure-identity (==1.25.1)",
    "pyqt6 (==6.10.0)",
    "pyqt6-sip (==13.10.2)",
    "python-dotenv (==1.1.1)",
    "python-bcrypt (==0.3.2)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
