from PyQt6.QtWidgets import QVBoxLayout
from PyQt6.QtWidgets import QHBoxLayout
from PyQt6.QtWidgets import QLabel
from PyQt6.QtWidgets import QPushButton
from PyQt6.QtWidgets import QLineEdit
from PyQt6.QtWidgets import QScrollArea
from PyQt6.QtWidgets import QWidget

from ui.tabs.base import BaseTab
from ui.core.revenue_generation import RevenueGeneration
from ui.core.autogen_ticket_num import autogen_ticket_num


class PostTab(BaseTab):
    def __init__(self, api_handler):
        self.ticket_input = None
        self.vendor_id_input = None
        self.phone_input = None
        self.datetime_input = None
        self.first_name_input = None
        self.middle_name_input = None
        self.last_name_input = None
        self.address_input = None
        self.city_input = None
        self.state_input = None
        self.products_layout = None
        self.remove_product_btn = None
        self.add_product_btn = None
        self.clear_btn = None
        self.revenue_generation = None
        self.status_label = None
        self.create_btn = None

        self.product_sections = []
        self.product_counter = 1

        super().__init__(api_handler, "post")

        self.setup_button_connections()

    def setup_ui(self):
        """
        :purpose: initializes the "Create New Record" tab
        :return: None
        :author(s): Joe Lee
        """
        # Enable scrolling for when the content exceeds the height of the window
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll_content = QWidget()
        layout = QVBoxLayout(scroll_content)

        # Line 0 Creation: Vendor Information on left + Ticket Number on right
        line0_layout = QHBoxLayout()

        # Vendor Information title
        title = QLabel("Vendor Information")
        title.setObjectName("post_title")
        line0_layout.addWidget(title)

        # Push to the right
        line0_layout.addStretch()

        # Ticket Number on right: Read-only
        line0_layout.addWidget(QLabel("Ticket Number:"))
        self.ticket_input = QLineEdit()
        self.update_ticket_number()
        self.ticket_input.setReadOnly(True)
        self.ticket_input.setFixedWidth(240)
        line0_layout.addWidget(self.ticket_input)

        # Ends creation and adds line0_layout to window
        layout.addLayout(line0_layout)

        # Line 1 Creation: Vendor ID + Phone Number + Date and Time
        line1_layout = QHBoxLayout()

        # Vendor ID
        line1_layout.addWidget(QLabel("Vendor ID:"))
        self.vendor_id_input = QLineEdit()
        self.vendor_id_input.setPlaceholderText("4 INTS")
        self.vendor_id_input.setMaxLength(4)
        self.vendor_id_input.setFixedWidth(80)
        line1_layout.addWidget(self.vendor_id_input)

        # Phone Number
        line1_layout.addWidget(QLabel("Phone Number:"))
        self.phone_input = QLineEdit()
        self.phone_input.setPlaceholderText("12 INTS")
        self.phone_input.setMaxLength(12)
        self.phone_input.setFixedWidth(150)
        line1_layout.addWidget(self.phone_input)

        # Date and Time - Read-only
        line1_layout.addWidget(QLabel("Date and Time:"))
        self.datetime_input = QLineEdit()
        self.datetime_input.setText("Autogenerated") # todo: SXC-21
        self.datetime_input.setReadOnly(True)
        line1_layout.addWidget(self.datetime_input)

        # Ends creation and adds line1_layout to window
        layout.addLayout(line1_layout)

        # Line 2: First Name + Middle Name + Last Name
        line2_layout = QHBoxLayout()

        # First Name
        line2_layout.addWidget(QLabel("First Name:"))
        self.first_name_input = QLineEdit()
        self.first_name_input.setPlaceholderText("30 chars")
        self.first_name_input.setMaxLength(30)
        self.first_name_input.setMinimumWidth(263)
        line2_layout.addWidget(self.first_name_input)

        # Middle Name
        line2_layout.addWidget(QLabel("Middle Name:"))
        self.middle_name_input = QLineEdit()
        self.middle_name_input.setPlaceholderText("10 chars")
        self.middle_name_input.setMaxLength(10)
        self.middle_name_input.setMinimumWidth(103)
        line2_layout.addWidget(self.middle_name_input)

        # Last Name
        line2_layout.addWidget(QLabel("Last Name:"))
        self.last_name_input = QLineEdit()
        self.last_name_input.setPlaceholderText("30 chars")
        self.last_name_input.setMaxLength(30)
        self.last_name_input.setMinimumWidth(263)
        line2_layout.addWidget(self.last_name_input)

        # End creation and adds line 2 to the window
        layout.addLayout(line2_layout)

        # Line 3: Address + City + State
        line3_layout = QHBoxLayout()

        # Address
        line3_layout.addWidget(QLabel("Address:"))
        self.address_input = QLineEdit()
        self.address_input.setPlaceholderText("Street address")
        self.address_input.setMaxLength(255)
        line3_layout.addWidget(self.address_input)

        # City
        line3_layout.addWidget(QLabel("City:"))
        self.city_input = QLineEdit()
        self.city_input.setPlaceholderText("City")
        self.city_input.setMaxLength(30)
        line3_layout.addWidget(self.city_input)

        # State
        line3_layout.addWidget(QLabel("State:"))
        self.state_input = QLineEdit()
        self.state_input.setPlaceholderText("ST")
        self.state_input.setMaxLength(2)
        self.state_input.setFixedWidth(50)
        line3_layout.addWidget(self.state_input)

        # Zip Code
        line3_layout.addWidget(QLabel("Zip Code:"))
        self.zip_input = QLineEdit()
        self.zip_input.setPlaceholderText("XXXXX")
        self.zip_input.setMaxLength(5)
        self.zip_input.setFixedWidth(70)
        line3_layout.addWidget(self.zip_input)

        # End creation and adds line3_layout to the window
        layout.addLayout(line3_layout)

        # HR Line between Vendor and Product sections
        hr1 = QLabel()
        hr1.setObjectName("hr")
        layout.addWidget(hr1)

        # Product Information title
        product_title = QLabel("Product Information")
        product_title.setObjectName("post_title")
        layout.addWidget(product_title)

        # Product sections container
        self.products_layout = QVBoxLayout()

        # Add the first two product sections by default
        self.add_product_section()
        self.add_product_section()

        layout.addLayout(self.products_layout)

        # Product Line Management buttons
        add_remove_layout = QHBoxLayout()

        # Remove Product Line button
        self.remove_product_btn = QPushButton("Remove Product Line")
        add_remove_layout.addWidget(self.remove_product_btn)

        # Push to the right
        add_remove_layout.addStretch()

        # Add Product Line button
        self.add_product_btn = QPushButton("Add Product Line")
        add_remove_layout.addWidget(self.add_product_btn)

        layout.addLayout(add_remove_layout)
        layout.addStretch(1)

        # HR Line between Product and Revenue sections
        hr2 = QLabel()
        hr2.setObjectName("hr")
        layout.addWidget(hr2)

        # Revenue Sharing section
        revenue_title = QLabel("Revenue Sharing")
        revenue_title.setObjectName("post_title")
        layout.addWidget(revenue_title)

        self.revenue_generation = RevenueGeneration()
        layout.addWidget(self.revenue_generation)

        # HR Line to separate buttons at the bottom
        hr3 = QLabel()
        hr3.setObjectName("hr")
        layout.addWidget(hr3)

        # Buttons at bottom - Clear left, Status center, Create right
        btn_layout = QHBoxLayout()

        # Clear Form button on left
        self.clear_btn = QPushButton("Clear Form")
        self.clear_btn.setObjectName("crit_large_btn")
        btn_layout.addWidget(self.clear_btn)

        # Push to center and add Status label
        btn_layout.addStretch()
        self.status_label = QLabel("Ready to create record")
        btn_layout.addWidget(self.status_label)
        btn_layout.addStretch()

        # Action buttons
        action_btns_container = QWidget()
        action_btns_layout = QVBoxLayout(action_btns_container)

        self.print_btn = QPushButton("Print")
        self.export_btn = QPushButton("Export")
        self.pdf_btn = QPushButton("PDF")

        action_btns_layout.addWidget(self.print_btn)
        action_btns_layout.addWidget(self.export_btn)
        action_btns_layout.addWidget(self.pdf_btn)
        btn_layout.addWidget(action_btns_container)

        # Create Record button on right
        self.create_btn = QPushButton("Create Record")
        self.create_btn.setObjectName("large_btn")
        btn_layout.addWidget(self.create_btn)

        layout.addLayout(btn_layout)

        # Set up the scroll area
        scroll.setWidget(scroll_content)
        main_layout = QVBoxLayout(self)
        main_layout.addWidget(scroll)

    def add_product_section(self):
        """
        :purpose: adds additional product lines
        :return: None
        :author(s): Joe Lee
        """
        product_section = {}

        # Product section container
        section_widget = QWidget()
        section_layout = QVBoxLayout(section_widget)
        section_layout.setContentsMargins(0, 0, 0, 0)

        # Line 1: Product ID and Product Name
        line1_layout = QHBoxLayout()

        # Product ID - Fixed width for 10 integers
        line1_layout.addWidget(QLabel("Product ID:"))
        product_id_input = QLineEdit()
        product_id_input.setPlaceholderText("10 INTS")
        product_id_input.setMaxLength(10)
        product_id_input.setFixedWidth(120)
        line1_layout.addWidget(product_id_input)
        product_section['product_id'] = product_id_input

        # Product Name - Takes up remaining space
        line1_layout.addWidget(QLabel("Product Name:"))
        product_name_input = QLineEdit()
        product_name_input.setPlaceholderText("Product name")
        line1_layout.addWidget(product_name_input)
        product_section['product_name'] = product_name_input

        section_layout.addLayout(line1_layout)

        # Line 2: Notes, Price, Quantity
        line2_layout = QHBoxLayout()

        # Notes - Takes up most of the space
        line2_layout.addWidget(QLabel("Notes:"))
        notes_input = QLineEdit()
        notes_input.setPlaceholderText("Product notes")
        line2_layout.addWidget(notes_input)
        product_section['notes'] = notes_input

        # Price - Fixed width
        line2_layout.addWidget(QLabel("Price:"))
        price_input = QLineEdit()
        price_input.setPlaceholderText("$0.00")
        price_input.setFixedWidth(100)
        line2_layout.addWidget(price_input)
        product_section['price'] = price_input

        # Quantity - Fixed width (same as price)
        line2_layout.addWidget(QLabel("Quantity:"))
        quantity_input = QLineEdit()
        quantity_input.setPlaceholderText("0")
        quantity_input.setFixedWidth(100)
        line2_layout.addWidget(quantity_input)
        product_section['quantity'] = quantity_input

        section_layout.addLayout(line2_layout)

        # Add to container
        self.products_layout.addWidget(section_widget)
        self.product_sections.append(product_section)
        self.product_counter += 1

    def remove_product_section(self):
        """
        :purpose: removes added product lines
        :return: None
        :author(s): Joe Lee
        """
        if len(self.product_sections) > 2:
            self.product_sections.pop()
            last_widget = self.products_layout.itemAt(self.products_layout.count() - 1).widget()

            self.products_layout.removeWidget(last_widget)
            last_widget.deleteLater()

            self.product_counter -= 1

            # Update status
            self.status_label.setText(f"Removed product line. Total: {len(self.product_sections)}")
        else:
            self.status_label.setText("Cannot remove the last 2 product lines")

    def setup_button_connections(self):
        """
        :purpose: links buttons with methods
        :return: None
        :author(s): Joe Lee
        """
        self.create_btn.clicked.connect(self.create_record)
        self.clear_btn.clicked.connect(self.clear_form)
        self.add_product_btn.clicked.connect(self.add_product_section)
        self.remove_product_btn.clicked.connect(self.remove_product_section)

    def create_record(self):
        """
        :purpose: initializes record to be posted to database
        :return: record
        :author(s): Joe Lee
        """
        # Get record
        record_data = {
            'ticket_number': self.ticket_input.text(),
            'vendor_id': self.vendor_id_input.text(),
            'phone': self.phone_input.text(),
            'datetime': self.datetime_input.text(),
            'first_name': self.first_name_input.text(),
            'middle_name': self.middle_name_input.text(),
            'last_name': self.last_name_input.text(),
            'address': self.address_input.text(),
            'city': self.city_input.text(),
            'state': self.state_input.text(),
            'zip': self.zip_input.text(),
            'products': []
        }

        # Get all product data
        for i, product_section in enumerate(self.product_sections):
            product_data = {
                'product_id': product_section['product_id'].text(),
                'product_name': product_section['product_name'].text(),
                'notes': product_section['notes'].text(),
                'price': product_section['price'].text(),
                'quantity': product_section['quantity'].text()
            }
            record_data['products'].append(product_data)

        # Get revenue sharing data from the existing component
        record_data['revenue_sharing'] = self.revenue_generation.get_revenue_data()

        # update status
        # todo: output should be justified alignment
        # todo: increase font size
        self.status_label.setText(
            f"Creating record"
            f"\nTicket: {record_data['ticket_number']} "
            f"\nVendor ID: {record_data['vendor_id']}"
            f"\nVendor Name: {record_data['first_name']} {record_data['last_name']}"
            f"\nProducts: {len(record_data['products'])}")
        print("Record Data:", record_data)

        return record_data

    def update_ticket_number(self):
        """
        :purpose: updates ticket number
        :return: None
        :author(s): Joe Lee
        """
        ticket_num = str(autogen_ticket_num())
        self.ticket_input.setText(ticket_num)

    def clear_form(self):
        """
        :purpose: clears all input fields
        :return: None
        :author(s): Joe Lee
        """
        self.ticket_input.clear()
        self.vendor_id_input.clear()
        self.phone_input.clear()
        self.first_name_input.clear()
        self.middle_name_input.clear()
        self.last_name_input.clear()
        self.address_input.clear()
        self.city_input.clear()
        self.state_input.clear()

        # Clear all product fields
        for product_section in self.product_sections:
            product_section['product_id'].clear()
            product_section['product_name'].clear()
            product_section['notes'].clear()
            product_section['price'].clear()
            product_section['quantity'].clear()

        self.revenue_generation.clear_revenue_data()

        self.status_label.setText("Form cleared")

        # Autopopulate again after clear fields (method calls)
        self.update_ticket_number()
        # todo: SXC-21
