from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QVBoxLayout
from PyQt6.QtWidgets import QHBoxLayout
from PyQt6.QtWidgets import QLabel
from PyQt6.QtWidgets import QLineEdit
from PyQt6.QtWidgets import QMessageBox
from PyQt6.QtWidgets import QPushButton
from PyQt6.QtWidgets import QScrollArea
from PyQt6.QtWidgets import QWidget
from PyQt6.QtGui import QIntValidator
from PyQt6.QtGui import QRegularExpressionValidator
from PyQt6.QtCore import QRegularExpression
from services.connectDB import DatabaseConnection


from ui.tabs.base import BaseTab
from ui.core.autogen_ticket_num import autogen_ticket_num
from ui.core.revenue_generation import RevenueGeneration


class PostTab(BaseTab):
    def __init__(self, api_handler):
        self.ticket_input = None
        self.vendor_id_input = None
        self.phone_input = None
        self.datetime_input = None
        self.first_name_input = None
        self.middle_name_input = None
        self.last_name_input = None
        self.address_input = None
        self.city_input = None
        self.state_input = None
        self.products_layout = None
        self.remove_product_btn = None
        self.add_product_btn = None
        self.clear_btn = None
        self.revenue_generation = None
        self.status_label = None
        self.create_btn = None

        self.product_sections = []
        self.product_counter = 1

        super().__init__(api_handler, "post")

        self.setup_button_connections()

    def setup_ui(self):
        """
        :purpose: initializes the "Create New Record" tab
        :return: None
        :author(s): Joe Lee
        """
        # Enable scrolling for when the content exceeds the height of the window
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll_content = QWidget()
        layout = QVBoxLayout(scroll_content)

        # Vendor Line 0 Creation: Vendor Information on left + Ticket Number on right
        vendor_section_row_0 = QHBoxLayout()

        # Vendor Information vendor_title
        vendor_title = QLabel("Vendor Information")
        vendor_title.setObjectName("post_title")
        vendor_section_row_0.addWidget(vendor_title)

        # Push to the right
        vendor_section_row_0.addStretch()

        # Ticket Number on right: Read-only
        vendor_section_row_0.addWidget(QLabel("Ticket Number:"))
        self.ticket_input = QLineEdit()
        self.ticket_input.setObjectName("READ_ONLY")
        self.update_ticket_number()
        self.ticket_input.setReadOnly(True)
        self.ticket_input.setFixedWidth(240)
        vendor_section_row_0.addWidget(self.ticket_input)

        # Ends creation and adds vendor_section_row_0 to window
        layout.addLayout(vendor_section_row_0)

        # Vendor Line 1 Creation: Vendor ID + Phone Number + Date and Time
        vendor_section_row_1 = QHBoxLayout()

        # Vendor ID
        vendor_section_row_1.addWidget(QLabel("Vendor ID:"))
        self.vendor_id_input = QLineEdit()
        self.vendor_id_input.setPlaceholderText("4 INTS")
        self.vendor_id_input.setMaxLength(4)
        self.vendor_id_input.setFixedWidth(80)
        self.vendor_id_input.setValidator(QIntValidator(0,9999, self))
        vendor_section_row_1.addWidget(self.vendor_id_input)

        # Phone Number
        vendor_section_row_1.addWidget(QLabel("Phone Number:"))
        self.phone_input = QLineEdit()
        self.phone_input.setPlaceholderText("12 INTS")
        self.phone_input.setMaxLength(12)
        self.phone_input.setFixedWidth(150)
        self.phone_input.setValidator(QIntValidator(0,2147483647, self))
        vendor_section_row_1.addWidget(self.phone_input)

        # Date and Time - Read-only
        vendor_section_row_1.addWidget(QLabel("Date and Time:"))
        self.datetime_input = QLineEdit()
        self.datetime_input.setObjectName("READ_ONLY")
        self.datetime_input.setText("Autogenerated") # todo: SXC-21
        self.datetime_input.setReadOnly(True)
        vendor_section_row_1.addWidget(self.datetime_input)

        # Ends creation and adds vendor_section_row_1 to window
        layout.addLayout(vendor_section_row_1)

        # Vendor Line 2: First Name + Middle Name + Last Name
        vendor_section_row_2 = QHBoxLayout()

        # First Name
        vendor_section_row_2.addWidget(QLabel("First Name:"))
        self.first_name_input = QLineEdit()
        self.first_name_input.setPlaceholderText("30 chars")
        self.first_name_input.setMaxLength(30)
        self.first_name_input.setMinimumWidth(263)
        alpha_validator = QRegularExpressionValidator(QRegularExpression("[A-Za-z ]+"))
        self.first_name_input.setValidator(alpha_validator)
        vendor_section_row_2.addWidget(self.first_name_input)

        # Middle Name
        vendor_section_row_2.addWidget(QLabel("Middle Name:"))
        self.middle_name_input = QLineEdit()
        self.middle_name_input.setPlaceholderText("10 chars")
        self.middle_name_input.setMaxLength(10)
        self.middle_name_input.setMinimumWidth(103)
        self.middle_name_input.setValidator(alpha_validator)
        vendor_section_row_2.addWidget(self.middle_name_input)

        # Last Name
        vendor_section_row_2.addWidget(QLabel("Last Name:"))
        self.last_name_input = QLineEdit()
        self.last_name_input.setPlaceholderText("30 chars")
        self.last_name_input.setMaxLength(30)
        self.last_name_input.setMinimumWidth(263)
        self.last_name_input.setValidator(alpha_validator)
        vendor_section_row_2.addWidget(self.last_name_input)

        # End creation and adds vendor_section_row_2 to the window
        layout.addLayout(vendor_section_row_2)

        # Vendor Line 3: Address + City + State
        vendor_section_row_3 = QHBoxLayout()

        # Address
        vendor_section_row_3.addWidget(QLabel("Address:"))
        self.address_input = QLineEdit()
        self.address_input.setPlaceholderText("Street address")
        self.address_input.setMaxLength(255)
        address_validator = QRegularExpressionValidator(QRegularExpression("[A-Za-z0-9 .,#-]+"))
        self.address_input.setValidator(address_validator)
        vendor_section_row_3.addWidget(self.address_input)

        # City
        vendor_section_row_3.addWidget(QLabel("City:"))
        self.city_input = QLineEdit()
        self.city_input.setPlaceholderText("City")
        self.city_input.setMaxLength(30)
        self.city_input.setValidator(alpha_validator)
        vendor_section_row_3.addWidget(self.city_input)

        # State
        vendor_section_row_3.addWidget(QLabel("State:"))
        self.state_input = QLineEdit()
        self.state_input.setPlaceholderText("ST")
        self.state_input.setMaxLength(2)
        self.state_input.setFixedWidth(50)
        self.state_input.setValidator(alpha_validator)
        vendor_section_row_3.addWidget(self.state_input)

        # Zip Code
        vendor_section_row_3.addWidget(QLabel("Zip Code:"))
        self.zip_input = QLineEdit()
        self.zip_input.setPlaceholderText("XXXXX")
        self.zip_input.setMaxLength(5)
        self.zip_input.setFixedWidth(70)
        zip_validator = QIntValidator(0, 99999, self)
        self.zip_input.setValidator(zip_validator)
        vendor_section_row_3.addWidget(self.zip_input)

        # End creation and adds vendor_section_row_3 to the window
        layout.addLayout(vendor_section_row_3)

        # HR Line between Vendor and Product sections
        hr1 = QLabel()
        hr1.setObjectName("hr")
        layout.addWidget(hr1)

        # Product Line 0: title
        product_section_row_0 = QHBoxLayout()

        # Product Information title
        product_title = QLabel("Product Information")
        product_title.setObjectName("post_title")
        product_section_row_0.addWidget(product_title)

        product_section_row_0.addStretch()

        # End creation and adds product_section_row_0 to the window
        layout.addLayout(product_section_row_0)

        # Product Line 1: Product sections container
        self.products_layout = QVBoxLayout()

        # Add the first two product sections by default
        self.add_product_section()
        self.add_product_section()

        layout.addLayout(self.products_layout)

        # Product Line Management buttons
        product_section_row_2 = QHBoxLayout()

        # Add Product Line button
        self.add_product_btn = QPushButton("Add Product Line")
        product_section_row_2.addWidget(self.add_product_btn)

        layout.addLayout(product_section_row_2)
        layout.addStretch(1)

        # HR Line between Product and Revenue sections
        hr2 = QLabel()
        hr2.setObjectName("hr")
        layout.addWidget(hr2)

        # combo_section_row_0
        combo_section_row_0 = QHBoxLayout()

        clear_section = QVBoxLayout()
        # Clear Form button on left bottom
        clear_section.addStretch()
        self.clear_btn = QPushButton("Clear Form")
        self.clear_btn.setObjectName("crit_large_btn")
        clear_section.addWidget(self.clear_btn)

        combo_section_row_0.addLayout(clear_section)
        combo_section_row_0.addStretch()

        # Revenue Sharing section
        revenue_widget = QWidget()
        revenue_section = QVBoxLayout(revenue_widget)
        revenue_title = QLabel("Revenue Sharing")
        revenue_title.setObjectName("post_title")
        revenue_section.addWidget(revenue_title, alignment=Qt.AlignmentFlag.AlignCenter)

        self.revenue_generation = RevenueGeneration()
        revenue_section.addWidget(self.revenue_generation)

        self.calc_btn = QPushButton("Calculate")
        self.calc_btn.setObjectName("post_title")
        revenue_section.addWidget(self.calc_btn)

        revenue_section.addStretch()

        combo_section_row_0.addWidget(revenue_widget)
        combo_section_row_0.addStretch()

        # Action buttons
        action_layout = QVBoxLayout()

        self.print_btn = QPushButton("Print")
        self.export_btn = QPushButton("Export")
        self.pdf_btn = QPushButton("PDF")

        action_layout.addWidget(self.print_btn)
        action_layout.addWidget(self.export_btn)
        action_layout.addWidget(self.pdf_btn)

        action_layout.addStretch()

        # Create Record button on right
        self.create_btn = QPushButton("Create Record")
        self.create_btn.setObjectName("large_btn")
        action_layout.addWidget(self.create_btn)

        combo_section_row_0.addLayout(action_layout)
        layout.addLayout(combo_section_row_0)

        # HR Line to separate buttons at the bottom
        hr3 = QLabel()
        hr3.setObjectName("hr")
        layout.addWidget(hr3)

        # Status Section
        status_container = QWidget()
        status_container.setObjectName("status_container")
        status_section = QHBoxLayout(status_container)

        # Align to center
        status_section.addStretch()
        self.status_label = QLabel("Ready to create record")
        status_section.addWidget(self.status_label, alignment=Qt.AlignmentFlag.AlignCenter)
        status_section.addStretch()

        layout.addWidget(status_container)

        # Set up the scroll area
        scroll.setWidget(scroll_content)
        main_layout = QVBoxLayout(self)
        main_layout.addWidget(scroll)

    def add_product_section(self):
        """
        :purpose: adds additional product lines
        :return: None
        :author(s): Joe Lee
        """
        product_section = {}

        # Product section container
        section_widget = QWidget()
        section_layout = QVBoxLayout(section_widget)
        section_layout.setContentsMargins(0, 0, 0, 0)

        # Line 1: Product ID and Product Name
        line1_layout = QHBoxLayout()

        # Product ID - Fixed width for 10 integers
        line1_layout.addWidget(QLabel("Product ID:"))
        product_id_input = QLineEdit()
        product_id_input.setPlaceholderText("10 INTS")
        product_id_input.setMaxLength(10)
        product_id_input.setFixedWidth(120)
        product_id_validator = QRegularExpressionValidator(QRegularExpression("[0-9]{0,10}"))
        product_id_input.setValidator(product_id_validator)
        line1_layout.addWidget(product_id_input)
        product_section['product_id'] = product_id_input

        # Product Name - Takes up remaining space
        line1_layout.addWidget(QLabel("Product Name:"))
        product_name_input = QLineEdit()
        product_name_input.setPlaceholderText("Product name")
        alpha_validator = QRegularExpressionValidator(QRegularExpression("[A-Za-z ]+"))
        product_name_input.setValidator(alpha_validator)
        line1_layout.addWidget(product_name_input)
        product_section['product_name'] = product_name_input

        # Add removal button for this specific line
        remove_btn = QPushButton("Remove Product Line")
        remove_btn.setObjectName("red_btn")
        remove_btn.clicked.connect(self.create_removal_handler(section_widget, product_section))
        line1_layout.addWidget(remove_btn)

        section_layout.addLayout(line1_layout)

        # Line 2: Notes, Price, Quantity
        line2_layout = QHBoxLayout()

        # Notes - Takes up most of the space
        line2_layout.addWidget(QLabel("Notes:"))
        notes_input = QLineEdit()
        notes_input.setPlaceholderText("Product notes")
        line2_layout.addWidget(notes_input)
        product_section['notes'] = notes_input

        # Price - Fixed width
        line2_layout.addWidget(QLabel("Price:"))
        price_input = QLineEdit()
        price_input.setPlaceholderText("$0.00")
        price_input.setFixedWidth(100)
        line2_layout.addWidget(price_input)
        product_section['price'] = price_input

        # Quantity - Fixed width (same as price)
        line2_layout.addWidget(QLabel("Quantity:"))
        quantity_input = QLineEdit()
        quantity_input.setPlaceholderText("0")
        quantity_input.setFixedWidth(100)
        quantity_input.setValidator(QIntValidator(0, 9999, self))
        line2_layout.addWidget(quantity_input)
        product_section['quantity'] = quantity_input

        section_layout.addLayout(line2_layout)

        # Add to container
        self.products_layout.addWidget(section_widget)
        self.product_sections.append(product_section)
        self.product_counter += 1

    def create_removal_handler(self, widget, product_section):
        def removal_handler():
            if self.show_remove_product_warning(product_section):
                self.remove_product_line(widget, product_section)

        return removal_handler

    def remove_product_line(self, widget, product_section):
        """
        :purpose: removes a specific product line
        :param widget: the widget to remove
        :param product_section: the product section data to remove
        :return: None
        """
        if product_section in self.product_sections:
            self.product_sections.remove(product_section)

        self.products_layout.removeWidget(widget)
        widget.deleteLater()

        self.product_counter -= 1
        self.status_label.setText(f"Removed product line. Total: {len(self.product_sections)}")

    def show_remove_product_warning(self, product_section):
        product_id = product_section['product_id'].text().strip()
        product_name = product_section['product_name'].text().strip()

        msg_box = QMessageBox(self)
        msg_box.setWindowTitle("Warning - Product Line Removal")
        msg_box.setText(f"Are you sure you want to remove this product line?\n{product_id} - {product_name}")
        confirm_btn = msg_box.addButton("Confirm", QMessageBox.ButtonRole.AcceptRole)
        cancel_btn = msg_box.addButton("Cancel", QMessageBox.ButtonRole.RejectRole)

        msg_box.setDefaultButton(confirm_btn)

        msg_box.exec()
        return msg_box.clickedButton() == confirm_btn

    def setup_button_connections(self):
        """
        :purpose: links buttons with methods
        :return: None
        :author(s): Joe Lee
        """
        self.create_btn.clicked.connect(self.create_record)
        self.clear_btn.clicked.connect(self.clear_form)
        self.add_product_btn.clicked.connect(self.add_product_section)
        # self.calc_btn.clicked.connect(self.update_revenue_fields) # todo: SXC-96

    def create_record(self):
        """
        :author(s): Joe Lee, Alexander Bubienko
        :purpose: gathers all text inputs and posts to Azure SQL database as a single record
        :return: record ID on success, -1 on error
        """
        try:
            # Get record data using existing method
            record_data = self._gather_record_data()
        
            # Validate required fields
            if not self._validate_required_fields(record_data):
                return -1
        
            # Post to database
            record_id = self._post_to_database(record_data)
        
            if record_id != -1:
                self.status_label.setText(f"Record created successfully! ID: {record_id}")
                self.clear_form()
                return record_id
            else:
                self.status_label.setText("Failed to create record")
                return -1
            
        except Exception as e:
            self.status_label.setText(f"Error creating record: {str(e)}")
            print(f"Database error: {e}")
            return -1

    def _gather_record_data(self):
        """
        :author(s): Alexander Bubienko
        :purpose: Gather all field data and convert empty strings to NULL
        :return: Dictionary containing vendor data, products data, and revenue data
        """
        # Vendor information
        vendor_data = {
            'ticket_number': self.ticket_input.text().strip() or "NULL",
            'vendor_id': self.vendor_id_input.text().strip() or "NULL",
            'phone': self.phone_input.text().strip() or "NULL",
            'datetime': self.datetime_input.text().strip() or "NULL",
            'first_name': self.first_name_input.text().strip() or "NULL",
            'middle_name': self.middle_name_input.text().strip() or "NULL",
            'last_name': self.last_name_input.text().strip() or "NULL",
            'address': self.address_input.text().strip() or "NULL",
            'city': self.city_input.text().strip() or "NULL",
            'state': self.state_input.text().strip() or "NULL"
        }
    
        # Product information
        products_data = []
        for i, product_section in enumerate(self.product_sections):
            product_data = {
                'product_id': product_section['product_id'].text().strip() or "NULL",
                'product_name': product_section['product_name'].text().strip() or "NULL",
                'notes': product_section['notes'].text().strip() or "NULL",
                'price': product_section['price'].text().strip() or "NULL",
                'quantity': product_section['quantity'].text().strip() or "NULL"
            }
            products_data.append(product_data)
    
        # Revenue sharing data
        revenue_data = self.revenue_generation.get_revenue_data()
    
        return {
            'vendor': vendor_data,
            'products': products_data,
            'revenue': revenue_data
        }

    def _validate_required_fields(self, record_data):
        """
        :author(s): Alexander Bubienko
        :purpose: Validate that required fields are filled
        :return: True if all required fields are valid, False otherwise
        """
        vendor = record_data['vendor']
        
        if not vendor['vendor_id'] or vendor['vendor_id'] == "NULL":
            self.status_label.setText("Error: Vendor ID is required")
            return False
            
        if not vendor['first_name'] or vendor['first_name'] == "NULL":
            self.status_label.setText("Error: First Name is required")
            return False
            
        if not vendor['last_name'] or vendor['last_name'] == "NULL":
            self.status_label.setText("Error: Last Name is required")
            return False
            
        return True

    def _post_to_database(self, record_data):
        """
        :author(s): Alexander Bubienko
        :purpose: Convert product ID to be within 0-9999 range for the CHECK constraint
        :return: Valid product ID as integer, or None if invalid
        """
        try:
            # Import and use DatabaseConnection            
            db_connection = DatabaseConnection()
            
            # Establish connection
            result = db_connection.establish_connection()
            if result == -1:
                self.status_label.setText("Error: Failed to establish database connection")
                return -1
            
            cursor = db_connection.create_cursor()
            if not cursor:
                self.status_label.setText("Error: Failed to create database cursor")
                return -1
            
            try:
                # Start transaction
                cursor.execute("BEGIN TRANSACTION")
                
                # Insert vendor record into existing Vendors table
                vendor_sql = """
                INSERT INTO Vendors (vendor_id, phone_number, first_name, middle_name, last_name, address, city, state, zip_code)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """
                
                vendor_values = (
                    int(record_data['vendor']['vendor_id']) if record_data['vendor']['vendor_id'] != "NULL" else None,
                    self._convert_null(record_data['vendor']['phone']),
                    self._convert_null(record_data['vendor']['first_name']),
                    self._convert_null(record_data['vendor']['middle_name']),
                    self._convert_null(record_data['vendor']['last_name']),
                    self._convert_null(record_data['vendor']['address']),
                    self._convert_null(record_data['vendor']['city']),
                    self._convert_null(record_data['vendor']['state']),
                    95819  # Default zip code
                )
                
                print("Executing vendor insert...")
                cursor.execute(vendor_sql, vendor_values)
                
                # Get the vendor_id
                vendor_id = int(record_data['vendor']['vendor_id'])
                
                print(f"Vendor inserted with ID: {vendor_id}")
                
                # Insert product records into existing Products table
                for i, product in enumerate(record_data['products']):
                    if self._has_product_data(product):
                        # Convert product_id to be within 0-9999 range
                        product_id = self._convert_product_id(product['product_id'])
                        if product_id is None:
                            print(f"Skipping product {i+1} - invalid product ID")
                            continue
                            
                        product_sql = """
                        INSERT INTO Products (product_id, product_name, notes, price, quantity)
                        VALUES (?, ?, ?, ?, ?)
                        """
                        
                        product_values = (
                            product_id,
                            self._convert_null(product['product_name']),
                            self._convert_null(product['notes']),
                            self._convert_null(product['price']),
                            # Use validated quantity
                            self._convert_quantity(product['quantity'])
                        )
                        
                        print(f"Inserting product {i+1} with ID: {product_id}...")
                        cursor.execute(product_sql, product_values)
                
                # Commit transaction
                db_connection.db_connection.commit()
                print("Transaction committed successfully!")
                return vendor_id
                
            except Exception as e:
                # Rollback on error
                db_connection.db_connection.rollback()
                print(f"Database operation failed: {e}")
                raise e
                
            finally:
                cursor.close()
                db_connection.close_connection()
                
        except Exception as e:
            print(f"Database insertion error: {e}")
            return -1
    def _convert_product_id(self, product_id_str):
        """
        :author(s): Alexander Bubienko
        :purpose: Convert product ID to be within 0-9999 range for the CHECK constraint
        :return: Valid product ID as integer, or None if invalid
        """
        if product_id_str == "NULL" or not product_id_str:
            return None
        
        try:
            product_id = int(product_id_str)
            # Ensure it's within the CHECK constraint range (0-9999)
            if 0 <= product_id <= 9999:
                return product_id
            else:
                print(f"Product ID {product_id} is outside valid range")
                return None
        except (ValueError, TypeError):
            print(f"Invalid product ID: {product_id_str}")
            return None

    def _convert_quantity(self, quantity_str):
        """
        :author(s): Alexander Bubienko
        :purpose: Convert quantity to be within 0-9999 range for the CHECK constraint
        :return: Valid quantity as integer, or None if invalid
        """
        if quantity_str == "NULL" or not quantity_str:
            return None
        
        try:
            quantity = int(quantity_str)
            # Ensure it's within the CHECK constraint range (0-9999)
            if 0 <= quantity <= 9999:
                return quantity
            else:
                print(f"Quantity {quantity} is outside valid range (0-9999)")
                return None
        except (ValueError, TypeError):
            print(f"Invalid quantity: {quantity_str}")
            return None
    
    def _convert_null(self, value):
        """
        :author(s): Alexander Bubienko
        :purpose: Convert "NULL" string to actual None for database NULL
        :return: None if value is "NULL", otherwise the original value
        """
        return None if value == "NULL" else value

    def _has_product_data(self, product):
        """
        :author(s): Alexander Bubienko
        :purpose: Check if product has any data (not all fields are NULL/empty)
        :return: True if product has at least one non-NULL field, False otherwise
        """
        return any(field != "NULL" and field for field in product.values())

    def _has_revenue_data(self, revenue_data):
        """
        :author(s): Alexander Bubienko
        :purpose: Check if revenue data exists
        :return: True if revenue data exists, False otherwise
        """
        return bool(revenue_data)

    def update_ticket_number(self):
        """
        :purpose: updates ticket number
        :return: None
        :author(s): Joe Lee
        """
        ticket_num = str(autogen_ticket_num())
        self.ticket_input.setText(ticket_num)

    def clear_form(self):
        """
        :purpose: clears all input fields, resets the product lines to 2
        :return: None
        :author(s): Joe Lee
        """
        self.ticket_input.clear()
        self.vendor_id_input.clear()
        self.phone_input.clear()
        self.first_name_input.clear()
        self.middle_name_input.clear()
        self.last_name_input.clear()
        self.address_input.clear()
        self.city_input.clear()
        self.state_input.clear()

        # Clear all product fields
        while self.products_layout.count():
            child = self.products_layout.takeAt(0)
            if child.widget():
                child.widget().deleteLater()

        self.product_sections.clear()
        self.product_counter = 1

        self.add_product_section()
        self.add_product_section()

        self.revenue_generation.clear_revenue_data()

        self.status_label.setText("Form cleared")

        # Autopopulate again after clear fields (method calls)
        self.update_ticket_number()
        # todo: SXC-21
