from .val_address import val_address
from .val_check_does_not_exist import val_check_does_not_exists
from .val_city import val_city
from .val_datetime import val_datetime
from .val_fl_name import val_fl_name
from .val_m_name import val_m_name
from .val_password import val_password
from .val_phone_number import val_phone_number
from .val_price import val_price
from .val_product_id import val_product_id
from .val_product_name import val_product_name
from .val_product_type import val_product_type
from .val_quantity import val_quantity
from .val_rate import val_rate
from .val_state import val_state
from .val_username import val_username
from .val_vendor_id import val_vendor_id
from .val_zip import val_zip
