from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QVBoxLayout, QTabWidget
from PyQt6.QtWidgets import QHBoxLayout
from PyQt6.QtWidgets import QLabel
from PyQt6.QtWidgets import QPushButton
from PyQt6.QtWidgets import QLineEdit
from PyQt6.QtWidgets import QScrollArea
from PyQt6.QtWidgets import QWidget

from services.database_service import DatabaseService
from ui.tabs.base import BaseTab

class VendorsTab(BaseTab):
    def __init__(self, api_handler):
        self.tickets_section = []
        super().__init__(api_handler, "vendors")

    def setup_ui(self):
        """
        :purpose: initializes the "Create New Record" tab
        :return: None
        :author(s): Joe Lee
        """
        # Enable scrolling for when the content exceeds the height of the window
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll_content = QWidget()
        layout = QVBoxLayout(scroll_content)

        # Line 0 Creation
        header_section = QHBoxLayout()

        # Ticket Header
        title = QLabel("View Vendors")
        title.setObjectName("post_title")
        header_section.addWidget(title)

        # Push to the left
        header_section.addStretch()

        # Ends creation and adds header_section to window
        layout.addLayout(header_section)

        # HR Line between Vendor and Tickets sections
        hr1 = QLabel()
        hr1.setObjectName("hr")
        layout.addWidget(hr1)

        # Ticket Line 1: Tickets sections container
        self.tickets_layout = QVBoxLayout()

        layout.addLayout(self.tickets_layout)

        tickets_section = QHBoxLayout()

        layout.addLayout(tickets_section)
        layout.addStretch()

        vendor_section_row_3 = QHBoxLayout()
        self.update_btn = QPushButton("Update")
        vendor_section_row_3.addWidget(self.update_btn)
        layout.addLayout(vendor_section_row_3)

        # HR Line to separate buttons at the bottom
        hr3 = QLabel()
        hr3.setObjectName("hr")
        layout.addWidget(hr3)

        # Status Section
        status_container = QWidget()
        status_container.setObjectName("status_container")
        status_section = QHBoxLayout(status_container)

        # Align to center
        status_section.addStretch()
        self.status_label = QLabel("Temporary")
        status_section.addWidget(self.status_label, alignment=Qt.AlignmentFlag.AlignCenter)
        status_section.addStretch()

        layout.addWidget(status_container)

        # Set up the scroll area
        scroll.setWidget(scroll_content)
        main_layout = QVBoxLayout(self)
        main_layout.addWidget(scroll)

        self.setup_button_connections()

    def add_user_section(self):
        """
        :purpose: adds ticket lines
        :return: None
        :author(s): Joe Lee
        """
        tickets_section = {}

        # Ticket section container
        section_widget = QWidget()
        section_layout = QVBoxLayout(section_widget)
        section_layout.setContentsMargins(0, 0, 0, 0)

        # Vendor Line 1 Creation: Vendor ID + Phone Number + Date and Time
        vendor_section_row_1 = QHBoxLayout()

        # Vendor ID
        vendor_section_row_1.addWidget(QLabel("Vendor ID:"))
        vendor_id_input = QLineEdit()
        vendor_id_input.setPlaceholderText("4 INTS")
        vendor_id_input.setObjectName("READ_ONLY")
        vendor_id_input.setReadOnly(True)
        vendor_id_input.setMaxLength(4)
        vendor_id_input.setFixedWidth(80)
        vendor_section_row_1.addWidget(vendor_id_input)

        # Phone Number
        vendor_section_row_1.addWidget(QLabel("Phone Number:"))
        phone_input = QLineEdit()
        phone_input.setPlaceholderText("12 INTS")
        phone_input.setObjectName("READ_ONLY")
        phone_input.setReadOnly(True)
        phone_input.setMaxLength(12)
        phone_input.setFixedWidth(150)
        vendor_section_row_1.addWidget(phone_input)

        # Date and Time - Read-only
        vendor_section_row_1.addWidget(QLabel("Date and Time:"))
        datetime_input = QLineEdit()
        datetime_input.setText("Autogenerated")
        datetime_input.setObjectName("READ_ONLY")
        datetime_input.setReadOnly(True)
        vendor_section_row_1.addWidget(datetime_input)

        # Ends creation and adds vendor_section_row_1 to window
        section_layout.addLayout(vendor_section_row_1)

        # Vendor Line 2: First Name + Middle Name + Last Name
        vendor_section_row_2 = QHBoxLayout()

        # First Name
        vendor_section_row_2.addWidget(QLabel("First Name:"))
        first_name_input = QLineEdit()
        first_name_input.setPlaceholderText("30 chars")
        first_name_input.setObjectName("READ_ONLY")
        first_name_input.setReadOnly(True)
        first_name_input.setMaxLength(30)
        first_name_input.setMinimumWidth(263)
        vendor_section_row_2.addWidget(first_name_input)

        # Middle Name
        vendor_section_row_2.addWidget(QLabel("Middle Name:"))
        middle_name_input = QLineEdit()
        middle_name_input.setPlaceholderText("10 chars")
        middle_name_input.setObjectName("READ_ONLY")
        middle_name_input.setReadOnly(True)
        middle_name_input.setMaxLength(10)
        middle_name_input.setMinimumWidth(103)
        vendor_section_row_2.addWidget(middle_name_input)

        # Last Name
        vendor_section_row_2.addWidget(QLabel("Last Name:"))
        last_name_input = QLineEdit()
        last_name_input.setPlaceholderText("30 chars")
        last_name_input.setObjectName("READ_ONLY")
        last_name_input.setReadOnly(True)
        last_name_input.setMaxLength(30)
        last_name_input.setMinimumWidth(263)
        vendor_section_row_2.addWidget(last_name_input)

        # End creation and adds vendor_section_row_2 to the window
        section_layout.addLayout(vendor_section_row_2)

        # Vendor Line 3: Address + City + State
        vendor_section_row_3 = QHBoxLayout()

        # Address
        vendor_section_row_3.addWidget(QLabel("Address:"))
        address_input = QLineEdit()
        address_input.setPlaceholderText("Street address")
        address_input.setObjectName("READ_ONLY")
        address_input.setReadOnly(True)
        address_input.setMaxLength(255)
        vendor_section_row_3.addWidget(address_input)

        # City
        vendor_section_row_3.addWidget(QLabel("City:"))
        city_input = QLineEdit()
        city_input.setPlaceholderText("City")
        city_input.setObjectName("READ_ONLY")
        city_input.setReadOnly(True)
        city_input.setMaxLength(30)
        vendor_section_row_3.addWidget(city_input)

        # State
        vendor_section_row_3.addWidget(QLabel("State:"))
        state_input = QLineEdit()
        state_input.setPlaceholderText("ST")
        state_input.setObjectName("READ_ONLY")
        state_input.setReadOnly(True)
        state_input.setMaxLength(2)
        state_input.setFixedWidth(50)
        vendor_section_row_3.addWidget(state_input)

        # Zip Code
        vendor_section_row_3.addWidget(QLabel("Zip Code:"))
        zip_input = QLineEdit()
        zip_input.setPlaceholderText("XXXXX")
        zip_input.setObjectName("READ_ONLY")
        zip_input.setReadOnly(True)
        zip_input.setMaxLength(5)
        zip_input.setFixedWidth(70)
        vendor_section_row_3.addWidget(zip_input)

        # End creation and adds vendor_section_row_3 to the window
        section_layout.addLayout(vendor_section_row_3)

        line3_layout = QHBoxLayout()
        # btns
        self.view_btn = QPushButton("View")
        line3_layout.addWidget(self.view_btn)
        self.edit_btn = QPushButton("Edit")
        self.edit_btn.setObjectName("red_btn")
        line3_layout.addWidget(self.edit_btn)
        self.del_btn = QPushButton("Delete")
        self.del_btn.setObjectName("red_btn")
        line3_layout.addWidget(self.del_btn)

        section_layout.addLayout(line3_layout)
        # HR Line between Vendor and Product sections
        hr = QLabel()
        hr.setObjectName("hr")
        section_layout.addWidget(hr)

        # Add to container
        self.tickets_layout.addWidget(section_widget)
        self.tickets_section.append(tickets_section)

    def remove_ticket_section(self):
        """
        :purpose: removes and clears all ticket sections
        :return: None
        :author(s): Joe Lee
        """
        # Remove all widgets from the layout
        for i in reversed(range(self.tickets_layout.count())):
            widget = self.tickets_layout.itemAt(i).widget()
            if widget:
                self.tickets_layout.removeWidget(widget)
                widget.deleteLater()

        # Clear the tickets_section list
        self.tickets_section.clear()

        # Update status
        self.status_label.setText("All tickets cleared")

    def fetch_on_clicked(self):
        """
        :purpose: calls fetch method and adds ticket sections
        :return: None
        :author(s): Joe Lee
        """
        self.remove_ticket_section()
        tickets = self.fetch()
        if not tickets:
            self.status_label.setText(f"Found no tickets")
        else:
            for ticket in tickets:
                self.add_user_section()

    def fetch(self):
        """
        :purpose: fetches all tickets with status=="OPEN" from Consignments table
        :return: list of tickets
        :author(s): Joe Lee
        """
        try:
            db = DatabaseService()
            conn = db.connect()
            cursor = conn.create_cursor()

            query = f"""
                    SELECT *
                    FROM Vendors
                    ORDER BY vendor_id ASC
                    """
            cursor.execute(query)
            results = cursor.fetchall()
            print(results)

            tickets = []
            for row in results:
                tickets.append({
                    'user_id': row[0],
                    'first_name': row[1],
                    'last_name': row[2]
                })
            return tickets
        except Exception as e:
            print(f"Error fetching tickets: {e}")
            return []

    def setup_button_connections(self):
        """
        :purpose: links buttons with methods
        :return: None
        :author(s): Joe Lee
        """
        self.update_btn.clicked.connect(self.fetch_on_clicked)