from PyQt6.QtWidgets import QWidget
from PyQt6.QtWidgets import QVBoxLayout
from PyQt6.QtWidgets import QHBoxLayout
from PyQt6.QtWidgets import QLabel
from PyQt6.QtWidgets import QLineEdit
from PyQt6.QtCore import Qt

class RevenueGeneration(QWidget):
    def __init__(self):
        super().__init__()
        self.revenue_records = []
        self.setup_ui()

    def setup_ui(self):
        main_layout = QHBoxLayout(self)
        main_layout.setContentsMargins(0, 0, 0, 0)

        content_container = QVBoxLayout()

        # Create the 3column layout
        revenue_layout = QVBoxLayout()

        # Header row
        header_layout = QHBoxLayout()

        # Vendor header
        vendor_header = QLabel("Vendor")
        vendor_header.setAlignment(Qt.AlignmentFlag.AlignCenter)
        vendor_header.setFixedWidth(120)
        header_layout.addWidget(vendor_header)

        # Percentage header
        percentage_header = QLabel("Percentage")
        percentage_header.setAlignment(Qt.AlignmentFlag.AlignCenter)
        percentage_header.setFixedWidth(100)
        header_layout.addWidget(percentage_header)

        # Super X header
        super_x_header = QLabel("Super X")
        super_x_header.setAlignment(Qt.AlignmentFlag.AlignCenter)
        super_x_header.setFixedWidth(120)
        header_layout.addWidget(super_x_header)

        revenue_layout.addLayout(header_layout)

        # Create 4 rows
        self.revenue_records = []
        for i in range(4):
            record_layout = QHBoxLayout()
            record_layout.setSpacing(5)

            # Vendor rows
            vendor_input = QLineEdit()
            vendor_input.setText("Autogenerated")
            vendor_input.setReadOnly(True)
            vendor_input.setFixedWidth(130)
            record_layout.addWidget(vendor_input)

            # Percentage rows
            percentage_label = QLabel(["25%", "50%", "75%", "100%"][i])
            percentage_label.setObjectName("percentage_label")
            percentage_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
            percentage_label.setFixedWidth(80)
            record_layout.addWidget(percentage_label)

            # Super X rows
            super_x_input = QLineEdit()
            super_x_input.setText("Autogenerated")
            super_x_input.setReadOnly(True)
            super_x_input.setFixedWidth(130)
            record_layout.addWidget(super_x_input)

            revenue_layout.addLayout(record_layout)

            # Store references to the inputs
            self.revenue_records.append({
                'vendor': vendor_input,
                'percentage': percentage_label,
                'super_x': super_x_input
            })

        content_container.addLayout(revenue_layout)
        main_layout.addLayout(content_container)

        # Add stretch to push content to the left half
        main_layout.addStretch()

        # Add stretch to keep section "in place"
        revenue_layout.addStretch()

    def get_revenue_data(self):
        revenue_data = []
        for record in self.revenue_records:
            revenue_data.append({
                'vendor': record['vendor'].text(),
                'percentage': record['percentage'].text(),
                'super_x': record['super_x'].text()
            })
        return revenue_data

    def clear_revenue_data(self):
        for record in self.revenue_records:
            record['vendor'].clear()
            record['super_x'].clear()

    def set_revenue_data(self, revenue_data):
        for i, record in enumerate(revenue_data):
            if i < len(self.revenue_records):
                self.revenue_records[i]['vendor'].setText(record.get('vendor', ''))
                self.revenue_records[i]['super_x'].setText(record.get('super_x', ''))