name: Release to .EXE

on:
  release:
    types: [released]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Poetry
      shell: powershell
      run: |
        (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python - --version 2.2.1
        echo "$env:APPDATA\Python\Scripts" | Out-File -Append -FilePath $env:GITHUB_PATH
    
    - name: Install dependencies (application)
      shell: powershell
      env:
        POETRY_VIRTUALENVS_CREATE: "false"
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest PyQt6 pytest-qt
        poetry install

    - name: Install dependencies (pyinstaller)
      shell: powershell
      env:
        POETRY_VIRTUALENVS_CREATE: "false"
      run: |
        python -m pip install pyinstaller

    - name: Build to .EXE/ Package Data
      shell: powershell
      run: |
        pyinstaller SXC.py `
        -w `
        --noupx `
        --add-data "./ui/themes;./ui/themes" `
        --add-data "./src/SPOT_CR.csv;./src" `
        --add-data "./src/imgs/*.png;./src/imgs" `

    - name: Move user-facing files to root
      shell: powershell
      run: | 
        Move-Item -Path "./dist/SXC/_internal/ui" -Destination "./dist/SXC"

    - name: Compress to single folder
      shell: powershell
      run: | 
        Compress-Archive -Path "./dist/SXC" -DestinationPath "./dist/SXC_${{ github.event.release.tag_name }}_win_x64.zip"

    - name: Build Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./dist/SXC_${{ github.event.release.tag_name }}_win_x64.zip"
        allowUpdates: true
